### ISSUE TITLE
News archive page

### ISSUE THREAD

**Issue by knuckles-echidna** [AlexZozulia/graduation-project#18]
1. Изображения без иискажений размера
2. Размеры и обтекания элементов (ссылки, текст и прочее)
3. Красный блок сверху ("юмор") - ссылка
4. Тень соц. иконкам (fb, vk, twi)
5. Краная рамка вокруг правого блока

**Comment by knuckles-echidna** [comment]
https://www.web-savvy-marketing.com/category/wordpress/ - пример разметки категории

**Comment by julite79** [comment]
done
